---
title: "About Me"
author: "Reuven"
date: "11/9/2021"
output: html_document
---

## Robert (Reuven) Derner
### Contact info:

raderner@gmail.com
rderner@mail.smu.edu
213-632-6305

## Summary of Qualifications

Possess great communication skills
Ability to consult, influence, persuade, adapt, and negotiate  
Organized and detail oriented, analytical, conscientious, thorough
A reliable, dependable professional with a strong work ethic and high integrity 

### Software Proficiency

Oracle SQL Developer, Vertica, SQL Workbench, Rapid SQL, MS Suite, SAS, R, Python, HP Service Manager, HP Quality Center, JIRA, Cloudera, Impala, Hive, Hadoop, Tableau, Cognos 10.22

## Experience
### Flagship Credit Acceptance LLC, Manager - Data Analytics, Coppell, TX 		
#### July 2021 - Present
Build and deploy PowerBi solutions to the Service Line of business by eliminating end user computing efforts and provide uptodate and easily accessible self-service reporting
Coach and mentor fellow associates in SQL to develop their skill set and enhance team framework

### Mercedes-Benz Financial Services, Business Intelligence Analyst/Data Scientist, Fort Worth, TX   
#### April 2018–July 2021  
Build and deploy Cognos and Tableau solutions to automate end user computing manual efforts.
Collaborate with business partners to design, develop, test, and integrate new Data Marts & Data Warehousing efforts to into the Collections management framework.
Heavily utilize SQL to answer business questions and harmonize metrics for new and continuous solutions in enhancing our BI landscape. 
Collaborate with Data Science team to identify gaps in our vendor’s phone performance, derive training opportunities with our agent reporting, and correlate variables in our automatic dialer system.
Used statistical methods to propose reductions in operational expenditures in the product landscaped based on measures: delinquency, calls, & loss-based terms, customer tier as relates to sales.
Build analytic models using Python and SAS to understand and enhance customer loyalty measures.

### Citi, Business Analyst Lead, Irving, TX	      	         				 
#### July 2017– February 2018  
Deploy superior data skills, to identify & recommend new business engagements for SoD onboarding of new applications.
Perform operational business requests for the SoD platform solution and assist with risk reduction efforts
Lead the documentation effort for the Enterprise Entitlement Review System (EERS) Segregation of Duties (SoD) project. 
Updated Automation efforts for monthly metrics activities and lead metrics collection/reporting activities to senior management calls utilizing JIRA for project management, tracking, and reporting throughout our iterations.

### GM Financial, Data Analyst, Fort Worth, TX	      	         			
#### November 2016–June 2017  
Performed data cleansing and synchronizing activities to conduct consumer and commercial loan reviews.
Utilizes statistical sampling to perform analysis to support loan review tests of controls.
Developed regular and ad-hoc reports required for loan reviews and answering immediate business questions.
Identification and design of metrics for benchmarking activities for meeting risk criteria objectives.

### Fidelity Investments, Business Intelligence Analyst, NH & TX      July 2014–November 2016  
Assists peers in developing insights using Oracle SQL, Excel, and Statistical Analyst techniques for primary and secondary research, reporting, query drill down, forecasting, and modeling to support business requirements.
Identification of data sourcing strategies from the system of records, and development of test strategy to meet program objectives.
Ran daily stand-ups for scrum calls utilizing JIRA for project management, tracking, and reporting throughout our iterations.
Reviewed system requirements to develop and implement test scenarios, create test plans, and participated in the definition and execution of automated and/or manual test scripts.
Managing the logging and resolution of defects in collaboration with development partners, utilizing a standard process and HP Service Manager.

#### Education
University of North Texas								Denton, TX
Bachelors of Business Administration in Decision Sciences 			  May 2014
Undergraduate Certificate in Alternative Dispute Resolutions			May 2014

Southern Methodist University: Master's in Data Science
  Courses Taken: Doing Data Science